# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fram',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student_lang',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student_other',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
