# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='validated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='studentskill',
            old_name='validated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.IntegerField(choices=[('', '-----'), (1, 'Студент'), (2, 'Викладач'), (3, 'Роботодавець')], default=1),
        ),
    ]
