# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170507_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='english',
            field=models.IntegerField(choices=[(1, 'Низький: A1 - Elementary'), (2, 'Низький: A2 - Pre-Intermediate'), (3, 'Середній: B1 - Intermediate'), (4, 'Середній: B2 - Upper intermediate'), (5, 'Високий: C1 - Advanced'), (6, 'Високий: C2 - Proficient')], default=1),
        ),
    ]
