# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170408_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='category',
        ),
    ]
