# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170411_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gitHub',
            new_name='github',
        ),
    ]
