# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170411_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='validate_at',
            new_name='validated_at',
        ),
        migrations.RenameField(
            model_name='framework',
            old_name='validate_by',
            new_name='validated_by',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='validate_at',
            new_name='validated_at',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='validate_by',
            new_name='validated_by',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='validate_at',
            new_name='validated_at',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='validate_by',
            new_name='validated_by',
        ),
        migrations.RenameField(
            model_name='student_fram',
            old_name='validate_at',
            new_name='validated_at',
        ),
        migrations.RenameField(
            model_name='student_fram',
            old_name='validate_by',
            new_name='validated_by',
        ),
        migrations.RenameField(
            model_name='student_lang',
            old_name='validate_at',
            new_name='validated_at',
        ),
        migrations.RenameField(
            model_name='student_lang',
            old_name='validate_by',
            new_name='validated_by',
        ),
        migrations.RenameField(
            model_name='student_other',
            old_name='validate_at',
            new_name='validated_at',
        ),
        migrations.RenameField(
            model_name='student_other',
            old_name='validate_by',
            new_name='validated_by',
        ),
    ]
