# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170414_1621'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shudent_short',
            table='account_student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='account_student',
        ),
    ]
