# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_studentprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_validate',
        ),
    ]
